# Notes collected about R programming from various books.

R has five atomic types : **character, numeric, integer, complex and logical**.
Most basic type in R is a **vector**, collection of homogeneous type. 
On the other hand **list** can contain items of different type.

---

#### Numbers
Numbers are treated as double precision real number objects. If an integer is needed then that has to be specified explicitly using the letter *L*. Not a Number *NaN* and *Inf* are special numbers in R.

---

#### Attributes
Attributes of the objects can be accessed using the function **attributes()**. example attributes of R objects are names, dimensions, class, length etc.

### Vectors

In [9]:
x <- c(0.5, 0.6) # Numeric vector
x <- c(TRUE, FALSE) # logical vector
x <- c("a", "b", "c") # character
x <- 0:10 #integer
x <- c(0+1i, 2+4i) # complex

In [10]:
print(typeof(x))
print(class(x))

[1] "complex"
[1] "complex"


Mixing of the object types leads to coercion. R tries to coerce the types implicitly. One can also explicitly invoke coercion using the **as** functions.
If R cannot coerce then it will result in NA

In [13]:
y <- c("a", TRUE)
print(class(y))

y <- c(1.8, "a")
print(class(y))

x <- 0:4
print(class(x))

print(as.numeric(x))
print(as.logical(x))

x <- c("a", "b", "c")
print(as.numeric(x))

[1] "character"
[1] "character"
[1] "integer"
[1] 0 1 2 3 4
[1] FALSE  TRUE  TRUE  TRUE  TRUE


Warning message in print(as.numeric(x)):
"NAs introduced by coercion"

[1] NA NA NA


### Matrices

they are vectors with dimension attribute. 
matrices are created using the **matrix** keyword as shown below. 

In [14]:
m <- matrix(nrow=2, ncol=3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [18]:
# get the dimension of the matrix using dim function
print(dim(m))

# get the attributes of the matrix using attributes function
print(attributes(m))

# Matrices are created column wise. 
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

# Converting vector to matrix
m <- 1:10
dim(m) <- c(2,5)
print(m)

# Multiple vectors can be converted to matrix using cbind to concatenate as columns
# use rbind to concatenate them as rows. 
v1 <- 1:5
v2 <- 2:6
print(rbind(v1,v2))
print(cbind(v1,v2))

[1] 2 5
$dim
[1] 2 5

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
   [,1] [,2] [,3] [,4] [,5]
v1    1    2    3    4    5
v2    2    3    4    5    6
     v1 v2
[1,]  1  2
[2,]  2  3
[3,]  3  4
[4,]  4  5
[5,]  5  6


### Lists
Can contain different types of items are are created using the **list** keyword.

In [20]:
x <- list(1, "a", TRUE, 1+4i)
print(x)
print(class(x))
print(attributes(x))
print(typeof(x))

# empty list
x <- vector("list", length=3)
print(x)
print(class(x))

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

[1] "list"
NULL
[1] "list"
[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[1] "list"


### Factors
Represents categorical data. Like an integer vector where each integer has a label. for example gender "male" and "female"
Can be created using the keyword **factor()**

In [22]:
x <- factor(c("male", "male", "female", "male", "female"))
print(x)
print(class(x))
print(typeof(x))

[1] male   male   female male   female
Levels: female male
[1] "factor"
[1] "integer"


## Subsetting R Objects

In [25]:
# Subsetting a vector
x <- c("a", "b", "c", "d", "e")
print(x[1])
print(x[2:3])
print(x[c(1,4,2)])
print(x[x > "a"])

[1] "a"
[1] "b" "c"
[1] "a" "d" "b"
[1] "b" "c" "d" "e"


In [29]:
# Subsetting a matrix
x <- matrix(1:6, 2, 3)
print(x)
print(x[1,2])
# If you set the drop value to FALSE the it retains the dimension
print(x[1,2, drop=FALSE])

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] 3
     [,1]
[1,]    3


In [32]:
# Subsetting lists
x <- list(foo = 1:4, bar = 0.6)
print(x)
print(x[[1]])
print(x[["bar"]])
print(x$bar)

# extracting multiple elements from a list
y <- list(foo = 1:4, bar = 20:29, baz="hello") # Returns a list whereas [[ ]] returns item. b
print(y[c(1,3)])

$foo
[1] 1 2 3 4

$bar
[1] 0.6

[1] 1 2 3 4
[1] 0.6
[1] 0.6
$foo
[1] 1 2 3 4

$baz
[1] "hello"



## Vectorized Operations

In [34]:
x <- 1:4
y <- 6:9
z <- x + y
z

[1]  7  9 11 13

In [36]:
x <- matrix(1:4, 2, 2)
y <- matrix(rep(10,4), 2, 2)
print(x * y)
print(x / y)
print(x %*% y)

     [,1] [,2]
[1,]   10   30
[2,]   20   40
     [,1] [,2]
[1,]  0.1  0.3
[2,]  0.2  0.4
     [,1] [,2]
[1,]   40   40
[2,]   60   60


# Dates and Times

Dates are stored internally as the number of days since 1970/01/01 and time as number of seconds since 1970/01/01. Dates are represented by the *Date* class and can be coerced from a character string using **as.Date()** function. Internal representation of the Date object can be seen using the function **unclass**.

In [40]:
x <- as.Date("1970/01/10")
x

[1] "1970-01-10"

In [41]:
unclass(x)

[1] 9

Times are represented by **POSIXlt** and **POSIXct**
* POSIXlt - a list of information like day of the week, day etc
* POSIXct - a large number

In [42]:
x <- Sys.time()
x

[1] "2019-10-30 21:52:27 CET"

In [43]:
p <- as.POSIXlt(x)
p

[1] "2019-10-30 21:52:27 CET"

In [44]:
unclass(p)

$sec
[1] 27.43751

$min
[1] 52

$hour
[1] 21

$mday
[1] 30

$mon
[1] 9

$year
[1] 119

$wday
[1] 3

$yday
[1] 302

$isdst
[1] 0

$zone
[1] "CET"

$gmtoff
[1] 3600

attr(,"tzone")
[1] ""     "CET"  "CEST"

In [45]:
unclass(x)

[1] 1572468747

In [48]:
p$mday

[1] 30

And for custom formatted time and date strings one can use the **strptime** function. 

In [49]:
datestring <- c("January 10, 2012 10:40")
x <- strptime(datestring, "%B %d, %Y %H:%M")
x

[1] "2012-01-10 10:40:00 CET"

### Operations on Dates and Times

Arithematic operations like + and - are allowed.
Comparision operations like == and <= are also allowed. 

In [51]:
x1 <- Sys.time()
Sys.sleep(3) # Sleep for 3 seconds.
x2 <- Sys.time()
x2 - x1

Time difference of 3.06676 secs

In [52]:
x1 <- as.Date("2012-03-01")
x2 <- as.Date("2019-08-04")
x2 - x1

Time difference of 2712 days

## Manageing Data Frames with the dplyr package

## Functions

* Functions are first class objects in R
* Functions can be passed as arguments to other functions.
* Functions can be nested. 

## Loop Functions

### lapply()
Loops over a list and evaluate a function on each element. 

In [1]:
x <- list(a = 1:5, b = rnorm(10))
x

$a
[1] 1 2 3 4 5

$b
 [1]  0.333992534  0.705464545  1.194129339  0.897660655 -0.338197142
 [6]  1.587304562 -0.002719118  4.010709049 -1.006969302 -1.716949084

In [2]:
lapply(x, mean)

$a
[1] 3

$b
[1] 0.5664426

How to pass arguments to the function 

In [4]:
x <- 1:4
print(x)
lapply(x, runif, min=0, max=4)

[1] 1 2 3 4


[[1]]
[1] 0.8536061

[[2]]
[1] 3.262570 2.163111

[[3]]
[1] 1.8063058 0.9678305 0.5493606

[[4]]
[1] 0.7405785 2.9634681 0.2917568 0.6704408

### sapply()

Difference between **lapply** and **sapply** is that **sapply** tries to simplify the output. 
* If the result is a list where every element is length 1, then a vector is returned
* If the result is a list where every element is a vector of the same length (> 1), a matrix is
returned.
* If it can’t figure things out, a list is returned

In [1]:
x <- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))

In [2]:
lapply(x, mean)

$a
[1] 2.5

$b
[1] 0.2697527

$c
[1] 0.9465366

$d
[1] 5.133117

In [8]:
res <- sapply(x, mean)
res

a         b         c         d 
2.5000000 0.2004205 1.3739807 5.2487881

#### split()

This function takes a vector or other objects and splits it into groups determined by a factor or list of factors. 

In [4]:
x <- c(rnorm(10), runif(10), rnorm(10,1))
f <- gl(3, 10)
lapply(split(x,f), mean)

$`1`
[1] 0.3586265

$`2`
[1] 0.5363715

$`3`
[1] 1.474587

A combination of **split** and **lapply** or **sapply** functions like map reduce. 

In [5]:
x <- c(rnorm(10), runif(10), rnorm(10,1))
f <- gl(3,10)
lapply(split(x,f), mean)

$`1`
[1] -0.1017938

$`2`
[1] 0.5120844

$`3`
[1] 1.053634

#### Splitting a dataframe

In [8]:
library(datasets)
head(airquality)
s <- split(airquality, airquality$Month)
str(s)

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

List of 5
 $ 5:'data.frame':	31 obs. of  6 variables:
  ..$ Ozone  : int [1:31] 41 36 12 18 NA 28 23 19 8 NA ...
  ..$ Solar.R: int [1:31] 190 118 149 313 NA NA 299 99 19 194 ...
  ..$ Wind   : num [1:31] 7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...
  ..$ Temp   : int [1:31] 67 72 74 62 56 66 65 59 61 69 ...
  ..$ Month  : int [1:31] 5 5 5 5 5 5 5 5 5 5 ...
  ..$ Day    : int [1:31] 1 2 3 4 5 6 7 8 9 10 ...
 $ 6:'data.frame':	30 obs. of  6 variables:
  ..$ Ozone  : int [1:30] NA NA NA NA NA NA 29 NA 71 39 ...
  ..$ Solar.R: int [1:30] 286 287 242 186 220 264 127 273 291 323 ...
  ..$ Wind   : num [1:30] 8.6 9.7 16.1 9.2 8.6 14.3 9.7 6.9 13.8 11.5 ...
  ..$ Temp   : int [1:30] 78 74 67 84 85 79 82 87 90 87 ...
  ..$ Month  : int [1:30] 6 6 6 6 6 6 6 6 6 6 ...
  ..$ Day    : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
 $ 7:'data.frame':	31 obs. of  6 variables:
  ..$ Ozone  : int [1:31] 135 49 32 NA 64 40 77 97 97 85 ...
  ..$ Solar.R: int [1:31] 269 248 236 101 175 314 276 267 272 175 ...
  

In [9]:
sapply(s, function(x) { colMeans(x[,c("Ozone", "Solar.R", "Wind")])})

5        6         7          8        9       
Ozone         NA        NA         NA       NA       NA
Solar.R       NA 190.16667 216.483871       NA 167.4333
Wind    11.62258  10.26667   8.941935 8.793548  10.1800