## Notes collected about R programming from various books.

R has five atomic types : **character, numeric, integer, complex and logical**.
Most basic type in R is a **vector**, collection of homogeneous type. 
On the other hand **list** can contain items of different type.

---

#### Numbers
Numbers are treated as double precision real number objects. If an integer is needed then that has to be specified explicitly using the letter *L*. Not a Number *NaN* and *Inf* are special numbers in R.

---

#### Attributes
Attributes of the objects can be accessed using the function **attributes()**. example attributes of R objects are names, dimensions, class, length etc.

### Vectors

In [9]:
x <- c(0.5, 0.6) # Numeric vector
x <- c(TRUE, FALSE) # logical vector
x <- c("a", "b", "c") # character
x <- 0:10 #integer
x <- c(0+1i, 2+4i) # complex

In [10]:
print(typeof(x))
print(class(x))

[1] "complex"
[1] "complex"


Mixing of the object types leads to coercion. R tries to coerce the types implicitly. One can also explicitly invoke coercion using the **as** functions.
If R cannot coerce then it will result in NA

In [13]:
y <- c("a", TRUE)
print(class(y))

y <- c(1.8, "a")
print(class(y))

x <- 0:4
print(class(x))

print(as.numeric(x))
print(as.logical(x))

x <- c("a", "b", "c")
print(as.numeric(x))

[1] "character"
[1] "character"
[1] "integer"
[1] 0 1 2 3 4
[1] FALSE  TRUE  TRUE  TRUE  TRUE


Warning message in print(as.numeric(x)):
"NAs introduced by coercion"

[1] NA NA NA


### Matrices

they are vectors with dimension attribute. 
matrices are created using the **matrix** keyword as shown below. 

In [14]:
m <- matrix(nrow=2, ncol=3)
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA

In [18]:
# get the dimension of the matrix using dim function
print(dim(m))

# get the attributes of the matrix using attributes function
print(attributes(m))

# Matrices are created column wise. 
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

# Converting vector to matrix
m <- 1:10
dim(m) <- c(2,5)
print(m)

# Multiple vectors can be converted to matrix using cbind to concatenate as columns
# use rbind to concatenate them as rows. 
v1 <- 1:5
v2 <- 2:6
print(rbind(v1,v2))
print(cbind(v1,v2))

[1] 2 5
$dim
[1] 2 5

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
   [,1] [,2] [,3] [,4] [,5]
v1    1    2    3    4    5
v2    2    3    4    5    6
     v1 v2
[1,]  1  2
[2,]  2  3
[3,]  3  4
[4,]  4  5
[5,]  5  6


### Lists
Can contain different types of items are are created using the **list** keyword.

In [20]:
x <- list(1, "a", TRUE, 1+4i)
print(x)
print(class(x))
print(attributes(x))
print(typeof(x))

# empty list
x <- vector("list", length=3)
print(x)
print(class(x))

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

[1] "list"
NULL
[1] "list"
[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[1] "list"


### Factors
Represents categorical data. Like an integer vector where each integer has a label. for example gender "male" and "female"
Can be created using the keyword **factor()**

In [22]:
x <- factor(c("male", "male", "female", "male", "female"))
print(x)
print(class(x))
print(typeof(x))

[1] male   male   female male   female
Levels: female male
[1] "factor"
[1] "integer"


## Subsetting R Objects

In [25]:
# Subsetting a vector
x <- c("a", "b", "c", "d", "e")
print(x[1])
print(x[2:3])
print(x[c(1,4,2)])
print(x[x > "a"])

[1] "a"
[1] "b" "c"
[1] "a" "d" "b"
[1] "b" "c" "d" "e"


In [29]:
# Subsetting a matrix
x <- matrix(1:6, 2, 3)
print(x)
print(x[1,2])
# If you set the drop value to FALSE the it retains the dimension
print(x[1,2, drop=FALSE])

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] 3
     [,1]
[1,]    3


In [32]:
# Subsetting lists
x <- list(foo = 1:4, bar = 0.6)
print(x)
print(x[[1]])
print(x[["bar"]])
print(x$bar)

# extracting multiple elements from a list
y <- list(foo = 1:4, bar = 20:29, baz="hello") # Returns a list whereas [[ ]] returns item. b
print(y[c(1,3)])

$foo
[1] 1 2 3 4

$bar
[1] 0.6

[1] 1 2 3 4
[1] 0.6
[1] 0.6
$foo
[1] 1 2 3 4

$baz
[1] "hello"



## Vectorized Operations

In [34]:
x <- 1:4
y <- 6:9
z <- x + y
z

[1]  7  9 11 13

In [36]:
x <- matrix(1:4, 2, 2)
y <- matrix(rep(10,4), 2, 2)
print(x * y)
print(x / y)
print(x %*% y)

     [,1] [,2]
[1,]   10   30
[2,]   20   40
     [,1] [,2]
[1,]  0.1  0.3
[2,]  0.2  0.4
     [,1] [,2]
[1,]   40   40
[2,]   60   60


# Dates and Times

Dates are stored internally as the number of days since 1970/01/01 and time as number of seconds since 1970/01/01. Dates are represented by the *Date* class and can be coerced from a character string using **as.Date()** function. Internal representation of the Date object can be seen using the function **unclass**.

In [40]:
x <- as.Date("1970/01/10")
x

[1] "1970-01-10"

In [41]:
unclass(x)

[1] 9

Times are represented by **POSIXlt** and **POSIXct**
* POSIXlt - a list of information like day of the week, day etc
* POSIXct - a large number

In [42]:
x <- Sys.time()
x

[1] "2019-10-30 21:52:27 CET"

In [43]:
p <- as.POSIXlt(x)
p

[1] "2019-10-30 21:52:27 CET"

In [44]:
unclass(p)

$sec
[1] 27.43751

$min
[1] 52

$hour
[1] 21

$mday
[1] 30

$mon
[1] 9

$year
[1] 119

$wday
[1] 3

$yday
[1] 302

$isdst
[1] 0

$zone
[1] "CET"

$gmtoff
[1] 3600

attr(,"tzone")
[1] ""     "CET"  "CEST"

In [45]:
unclass(x)

[1] 1572468747

In [48]:
p$mday

[1] 30